version: '3'

services:
  influx:
    image: 'influxdb'
    ports:
      - 8086
      - 8083

  grafana:
    image: 'grafana/grafana'
    ports:
      - 3000:3000

  telegraf:
    image: 'telegraf'
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf

  mqtt-broker:
    image: 'volantmq/volantmq'

  mqtt-producer:
    build: ./mqtt-producer/